server.port=8080
spring.kafka.bootstrap-servers=${Kafka__BootstrapServers:localhost:9092}
spring.kafka.producer.properties.max.block.ms=5000
spring.kafka.producer.properties.request.timeout.ms=4000
spring.kafka.producer.properties.delivery.timeout.ms=5000
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=true
springdoc.swagger-ui.path=/swagger
springdoc.api-docs.path=/swagger/v1/swagger.json
